node("linux"){
  stage("Get Repo from branch") {
    checkout scm
  }
  
  stage("Create Docker Image") {
    app = docker.build("peterkr/opsschool-project")
  }

  stage("verify Docker Image") 
  {
    sh "docker images"
  }

  stage("Push to DockerHub") {
    withDockerRegistry(credentialsId: 'dockerhub.peterkr', url: '') 
    {
      app.push()
    }
  }
}
